### ISSUE TITLE
Unresponsive : Title 'Retrohackathon' is not Adjusting According to windows Size

### ISSUE THREAD

**Issue by nishchalbasyal** [sanjaysah101/RetroAI-Quest-Hackathon#2]
![image](https://github.com/user-attachments/assets/b0bbdd00-58bb-41b6-bd3d-e756e1e52440)

**Comment by sanjaysah101** [comment]
Hi @nishchalbasyal, Could you please fix this issue and create a PR?

**Comment by nishchalbasyal** [comment]
I have solved the problem. checkout #3 and approved my request
